
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cryptocurrency-price-fetcher.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cryptocurrency-price-fetcher.name" . }}
    helm.sh/chart: {{ include "cryptocurrency-price-fetcher.chart" . }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "cryptocurrency-price-fetcher.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
